package controllers

func makeCommandExitCode(code string) int {
	switch code {
	case "RENDER_FAILED":
		return ExitRenderFailed
	case "RECIPE_FILE_NOT_FOUND", "READ_RECIPE_FAILED", "INVALID_RECIPE_JSON", "MISSING_SELECTIONS", "MISSING_SELECTION_ID",
		"UNKNOWN_LAYER_ID", "UNSUPPORTED_BODY_TYPE", "MISSING_SPRITE_FRAME", "READ_SPRITE_FRAME_FAILED",
		"ASSETS_DIRECTORY_NOT_FOUND", "READ_ASSETS_DIRECTORY_FAILED", "ASSETS_PATH_NOT_DIRECTORY",
		"MISSING_PACK_JSON", "READ_PACK_JSON_FAILED", "INVALID_PACK_JSON", "MISSING_SHEET_DEFINITIONS", "INVALID_SHEET_DEFINITION_JSON", "READ_SHEET_DEFINITIONS_FAILED":
		return ExitInvalidAssets
	default:
		return ExitGeneralError
	}
}
